name: CI
on : [push,pull_request]
jobs: 
  run-tests :
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST : localhost
      DATABASE_PORT : 5432
      DATABASE_USERNAME : postgres
      DATABASE_PASSWORD : postgres
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{env.DATABASE_PASSWORD}}
          POSTGRES_PORT : ${{env.DATABASE_PORT}}
          POSTGRES_HOST : ${{env.DATABASE_HOST}}
          POSTGRES_USERNAME : ${{env.DATABASE_USERNAME}}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name : Install Dependencies
        run: yarn
      - name : Run Tests
        run: yarn test